### ISSUE TITLE
Error importing

### ISSUE THREAD

**Issue by ticoti** [python273/telegraph#1]
the example script gives error importinga ( already made pip install telegraph)

python /home/scripts/telegraph.py
Traceback (most recent call last):
  File "/home/scripts/telegraph.py", line 1, in <module>
    from telegraph import Telegraph
  File "/home/scripts/telegraph.py", line 1, in <module>
    from telegraph import Telegraph
ImportError: cannot import name Telegraph

**Comment by python273** [comment]
You need to rename the script

**Comment by mercuree** [comment]
`python /home/scripts/telegraph.py`
This filename shadows telegraph package, so you are trying import yourself.
Try to rename your telegraph.py
