### ISSUE TITLE
TelegraphException: CONTENT_TOO_BIG

### ISSUE THREAD

**Issue by mengyyy** [python273/telegraph#21]
I found the max langth is about 10917 * 6.
If i use Chinese character the num will be 10917.
But i can put more than 20000 Chinese character in web telegra.ph.
Is there some reason for this difference?
```
from telegraph import Telegraph

telegraph = Telegraph()

telegraph.create_account(short_name="1337")


# this will success

telegraph.create_page('page_title', html_content='<p>{}</p>'.format("从"*10917))
# or 
telegraph.create_page('page_title', html_content='<p>{}</p>'.format("a"*10917 * 6))

# but this will failed 
# TelegraphException: CONTENT_TOO_BIG

telegraph.create_page('page_title', html_content='<p>{}</p>'.format("从"*10918))
# or 
telegraph.create_page('page_title', html_content='<p>{}</p>'.format("a"*10918 * 6))
```

**Comment by python273** [comment]
```python
>>> import telegraph
>>> print(json.dumps(telegraph.utils.html_to_nodes('<p>从从从</p>')))
[{"tag": "p", "children": ["\u4ece\u4ece\u4ece"]}]
```
I think the problem with converting utf-8 chars to json. You can try to add `, ensure_ascii=False` for `json.dumps` calls (https://stackoverflow.com/questions/18337407/saving-utf-8-texts-in-json-dumps-as-utf8-not-as-u-escape-sequence) and check if that works

**Comment by mengyyy** [comment]
> ```python
> >>> import telegraph
> >>> print(json.dumps(telegraph.utils.html_to_nodes('<p>从从从</p>')))
> [{"tag": "p", "children": ["\u4ece\u4ece\u4ece"]}]
> ```
> 
> I think the problem with converting utf-8 chars to json. You can try to add `, ensure_ascii=False` for `json.dumps` calls (https://stackoverflow.com/questions/18337407/saving-utf-8-texts-in-json-dumps-as-utf8-not-as-u-escape-sequence) and check if that works

Yes It works for Chinese
```
# success 
telegraph.create_page('page_title', html_content='<p>{}</p>'.format("从"*21834))
# https://telegra.ph/page-title-05-06-16

# CONTENT_TOO_BIG
telegraph.create_page('page_title', html_content='<p>{}</p>'.format("从"*21835))

# P.S.
# ACCESS_TOKEN_INVALID
telegraph.create_page('page_title', html_content='<p>{}</p>'.format("从"*29107))
```

**Comment by mengyyy** [comment]
Maybe add an option **ensure_ascii** will be better?

**Comment by python273** [comment]
I think we can set `, ensure_ascii=False` by default

**Comment by mengyyy** [comment]
Yeap~
