### ISSUE TITLE
Update PyPI package

### ISSUE THREAD

**Issue by javad94** [python273/telegraph#27]
Please update the PyPI package to include fix for #21.

**Comment by python273** [comment]
Uploaded

https://github.com/python273/telegraph/releases/tag/v1.4.1

**Comment by javad94** [comment]
Thanks.

**Comment by TemplateDestruction** [comment]
Seems, in latest release (2.1.0) these fixes are absence
https://github.com/python273/telegraph/blob/da629de7c00c3b8b0c7ab8ef4bf23caf419a3c6c/telegraph/api.py#L162
