### ISSUE TITLE
How can I upload images to telegraph via this library?

### ISSUE THREAD

**Issue by f126ck** [python273/telegraph#3]
Noob here.
I wanted to know if it was possible to make a telegraph article including photos/videos which I have got on my hard disk.

How can I upload them and show in the article?

Thanks

**Comment by python273** [comment]
It's not possible to upload photos/videos via API, but you can use this code

```
import requests


with open('/Users/python273/Desktop/123345.jpeg', 'rb') as f:
    print(
        requests.post(
            'http://telegra.ph/upload',
            files={'file': ('file', f, 'image/jpeg')}
        ).json()
        )
```

**Comment by f126ck** [comment]
Thank you very very very much :)

**Comment by mieburungdara** [comment]
how to use this in php?
```
import requests


with open('/Users/python273/Desktop/123345.jpeg', 'rb') as f:
    print(
        requests.post(
            'http://telegra.ph/upload',
            files={'file': ('file', f, 'image/jpeg')}  # image/gif, image/jpeg, image/jpg, image/png, video/mp4
        ).json()
    )
```

**Comment by deantipin** [comment]
@f126ck Could you, please, share your code?
What should I put instead of 'file'? - I've tried every possible combination of my file name and it doesn't work..

**Comment by deantipin** [comment]
@python273 

`telegraph = Telegraph()

telegraph.create_account(short_name='ico_inspector', author_name='ICO_inspector')


response = telegraph.create_page(
    title = coin_name,
    author_name='ICO_inspector',
    html_content=
    '<blockquote><strong><em>General information: </em></strong></blockquote>' +
    general_info(coin_general_info) +    
    '<aside>chart is here<aside>' +
    '<blockquote><strong><em>Upcoming events: </em></strong></blockquote>'  +
    ' '.join(events_formatted) +
    '<hr>a</hr>'
    
)

print('http://telegra.ph/{}'.format(response['path']))`

**Comment by deantipin** [comment]
@python273 Could you tell me, what would I change in order to make the post with picture?

``` Python
from telegraph import Telegraph

telegraph = Telegraph()

telegraph.create_account(short_name='1337')

response = telegraph.create_page(
    'Hey',
    html_content='<p>Hello, world!</p>'
)

with open('/Users/deantipin/picture.png', 'rb') as f:
    print(
        requests.post(
            'http://telegra.ph/upload',
            files={'Hey': ('Hey', f, 'image/png')}  # image/gif, image/jpeg, image/jpg, image/png, video/mp4
        ).json()
    )
print('http://telegra.ph/{}'.format(response['path']))
```

**Comment by qwerty432** [comment]
@deantipin maybe i'm late, but it should work

```
from telegraph import Telegraph

telegraph = Telegraph()

telegraph.create_account(short_name='1337')

with open('/Users/deantipin/picture.png', 'rb') as f:
    path = requests.post(
                    'http://telegra.ph/upload', files={'file': 
                                                        ('file', f, 
                                                        'image/jpeg')}).json().json()[0]['src']


response = telegraph.create_page(
    'Hey',
    html_content="<p>Hello, world!</p> <img src='{}'/>".format(path),

)

print('http://telegra.ph/{}'.format(response['path']))
```

**Comment by greatspoke** [comment]
Hello! Guys its possible posting to telegra.ph but from url via node js?
I need posting to telegraph picture not form hard disk, from url only
Thank you

**Comment by python273** [comment]
@greatspoke you can download the picture and upload to telegraph

**Comment by apcel** [comment]
Hey guys
Just in case telegraph has suddenly started returning "error: no files passed": it looks like telegraph has moved to https (finally!), so `http://telegra.ph/upload` from the examples above should be changed to `https://telegra.ph/upload`

**Comment by greatspoke** [comment]
I mean use with https://www.npmjs.com/package/telegraph-node
try
`[url=https://goo.gl/FHcL48]$12.00    NYX PROFESSIONAL MAKEUP Soft Matte Lip Cream Set No. 13[/url]`
` ph.createPage(token, 'sale_shop_bot', ['[url]https://goo.gl/FHcL48[/url]'],  {
        return_content: true
    }).then((result) => {
        console.log(result)
    })`

But not work(((

**Comment by GooDeeJaY** [comment]
Using **http** I'm getting: response **[200]** with `{"error":"No files passed"}`
Using **https** I'm getting: response **[500]**

What I'm doing wrong?

**Comment by macsunmood** [comment]
> It's not possible to upload photos/videos via API, but you can use this code
> 
> ```
> import requests
> 
> 
> with open('/Users/python273/Desktop/123345.jpeg', 'rb') as f:
>     print(
>         requests.post(
>             'http://telegra.ph/upload',
>             files={'file': ('file', f, 'image/jpeg')}  # image/gif, image/jpeg, image/jpg, image/png, video/mp4
>         ).json()
>     )
> ```

Hello, @python273! Have been trying to upload image via both `requests.post()` (as featured in your example) as well as `telegraph.upload.upload_file(f)` from your library, but keep always getting an error as follows:

> **SSLError: HTTPSConnectionPool(host='telegra.ph', port=443): Max retries exceeded with url: /upload (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')")))**

No googling of the error helped so far. :( Please, can anything be done about it ?

**Comment by python273** [comment]
Seems like `/upload` is not part of the API, so not really sure about 500 and other errors

> ```SSLError: HTTPSConnectionPool(host='telegra.ph', port=443): Max retries exceeded with url: /upload (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')")))```

Maybe `telegra.ph` is blocked for you, so you need to use proxy

**Comment by giangdinh** [comment]
I face this issue:  https://github.com/python273/telegraph/issues/36

Does anyone here face this? I do the same code that mentions this issue, it works fine for image but error for video/mp4.

**Comment by zogex** [comment]
> ```python
> print('http://telegra.ph/{}'.format(response['path']))
> ```

Maybe telegra.ph is blocked for you
Use te.legra.ph in this case

**Comment by zogex** [comment]
@GooDeeJaY 
Maybe telegra.ph is blocked for you
Use te.legra.ph in this case

**Comment by 227234** [comment]
https://github.com/python273/telegraph/issues/3#issuecomment-418197910

**Comment by 227234** [comment]
https://github.com/python273/telegraph/issues/3#issuecomment-583859146

**Comment by 227234** [comment]
https://github.com/python273/telegraph/issues/3#issuecomment-1017489272

**Comment by Maniac1488ss** [comment]
#53
