### ISSUE TITLE
What is the size limit for image/video??

### ISSUE THREAD

**Issue by avthetechpreneur** [python273/telegraph#31]
What is the size limit for image/video?? on telegra.ph

**Comment by giangdinh** [comment]
https://limits.tginfo.me/en

As I see in the link above, Telegraph has a limit of each particle size is up to 64 KiB, do not know the limit of a video or an image you upload.

**Comment by avthetechpreneur** [comment]
Ok so i tested it with different sizes telegraph allows upto 5mb of image, video files
