### ISSUE TITLE
ImportError: cannot import name 'Telegraph' from partially initialized module 'telegraph'

### ISSUE THREAD

**Issue by RenatohRibeiro** [python273/telegraph#34]
![image](https://user-images.githubusercontent.com/49354525/98977913-ec9a7680-24f7-11eb-8a80-db4b0d0058b9.png)
![image](https://user-images.githubusercontent.com/49354525/98977929-f2905780-24f7-11eb-8dd3-5514c8c12603.png)

**Comment by mercuree** [comment]
@RenatohRibeiro Try to rename your telegraph.py to a different name.

**Comment by RenatohRibeiro** [comment]
tks bro
