### ISSUE TITLE
hide link preview

### ISSUE THREAD

**Issue by f126ck** [python273/telegraph#4]
Hi! 
It's me again :) 

Not a real issue, so feel free to close/ban the issue even if no answer is available. 

I recently played with telegram bots and in the bot API there is a keyword, 'disable_web_page_preview' used to hide the preview. 
I wanted to know if there exist such a way to hide instant view article preview, showing only the button, since if I use that keyword, content is not previewed and whenever I click the link, my external Android browser fires up (which is bad because I want preview) 
Hope I've been clear, 
Thanks.

**Comment by python273** [comment]
¯\\\_(ツ)_/¯
