### ISSUE TITLE
No InstantView?

### ISSUE THREAD

**Issue by sixhobbits** [python273/telegraph#7]
When I create Telegraph articles using this wrapper and post to the mobile app, they do not get converted to Instant View.

Anyone know why?

**Comment by python273** [comment]
Just checked. It should work

![-](https://user-images.githubusercontent.com/3097956/27359599-4d257dd8-5625-11e7-8714-d36ffcee0ed9.jpg)

**Comment by JohnPlayerSpecial** [comment]
I have the same issue had by @sixhobbits.

Article is created fine, images are in the true position ( not at the end, issue fixed thanks  a lot!)

When I put in the html_content only text I have a nice instant view button... but when I insert images in the page Telegram Android Client doesn't show anymore IV button...

I tried different methods to add images, like

```
#html_content += '<figure><img src="{}"/><figcaption>Added on {}</figcaption></figure>'.format( photo_url,  timeAdded )
#html_content += '<img src="{}"/>'.format( photo_url )
html_content += '<figure><img src="{}"/><figcaption>{}</figcaption></figure>'.format(photo_url,timeAdded)
```

Can you point me out where we are wrong?
